// Generated by scripts/gen-palette.mjs from @catppuccin/palette.
// Catppuccin Latte，页面唯一的配色。

export const latte = {
	base: '#eff1f5',
	text: '#4c4f69',
	subtext0: '#6c6f85',
	overlay0: '#9ca0b0',
	mauve: '#8839ef',
};
