// Regenerates src/lib/palette.ts from @catppuccin/palette.
// Usage: node scripts/gen-palette.mjs
import { writeFileSync } from 'node:fs';
import { flavors } from '@catppuccin/palette';

const ACCENTS = [
	'rosewater', 'flamingo', 'pink', 'mauve', 'red', 'maroon', 'peach',
	'yellow', 'green', 'teal', 'sky', 'sapphire', 'blue', 'lavender',
];

const SURFACES = [
	'text', 'subtext1', 'subtext0',
	'overlay2', 'overlay1', 'overlay0',
	'surface2', 'surface1', 'surface0',
	'base', 'mantle', 'crust',
];

const FLAVORS = ['latte', 'frappe', 'macchiato', 'mocha'];

const union = (name, values) =>
	`export type ${name} =\n${values.map((v) => `\t| '${v}'`).join('\n')};\n`;

const out = [];
out.push('// Generated by scripts/gen-palette.mjs from @catppuccin/palette.');
out.push('// Do not edit by hand.');
out.push('');
out.push(union('AccentName', ACCENTS));
out.push(union('SurfaceName', SURFACES));
out.push(union('FlavorName', FLAVORS));
out.push('export interface Flavor {');
out.push('\tname: string;');
out.push('\tdark: boolean;');
out.push('\tcolors: Record<AccentName | SurfaceName, string>;');
out.push('}');
out.push('');
out.push('export const accentNames: AccentName[] = [');
out.push(ACCENTS.map((a) => `\t'${a}',`).join('\n'));
out.push('];');
out.push('');
out.push('export const flavorNames: FlavorName[] = [');
out.push(FLAVORS.map((f) => `\t'${f}',`).join('\n'));
out.push('];');
out.push('');
out.push('export const flavors: Record<FlavorName, Flavor> = {');
for (const key of FLAVORS) {
	const f = flavors[key];
	out.push(`\t${key}: {`);
	out.push(`\t\tname: ${JSON.stringify(f.name)},`);
	out.push(`\t\tdark: ${f.dark},`);
	out.push('\t\tcolors: {');
	for (const name of [...ACCENTS, ...SURFACES]) {
		out.push(`\t\t\t${name}: '${f.colors[name].hex}',`);
	}
	out.push('\t\t},');
	out.push('\t},');
}
out.push('};');
out.push('');

writeFileSync(new URL('../src/lib/palette.ts', import.meta.url), out.join('\n'));
console.log(`wrote src/lib/palette.ts (${FLAVORS.length} flavors)`);
