// Regenerates src/lib/palette.ts from @catppuccin/palette.
// Usage: node scripts/gen-palette.mjs
import { writeFileSync } from 'node:fs';
import { flavors } from '@catppuccin/palette';

// 页面只用 Catppuccin 标准的 Latte 配色
const USED = ['base', 'text', 'subtext0', 'overlay0', 'mauve'];

const latte = flavors.latte.colors;

const out = [
	'// Generated by scripts/gen-palette.mjs from @catppuccin/palette.',
	'// Catppuccin Latte，页面唯一的配色。',
	'',
	'export const latte = {',
	...USED.map((name) => `\t${name}: '${latte[name].hex}',`),
	'};',
	'',
];

writeFileSync(new URL('../src/lib/palette.ts', import.meta.url), out.join('\n'));
console.log('wrote src/lib/palette.ts (latte)');
